### ISSUE TITLE
Problema con url

### ISSUE THREAD

**Issue by kkoci** [data-tsunami/django-mercadopago#1]
Hola, me parece muy interesante tu proyecto, ahora mismo estoy implementando un custom checkout en mi app Django, aunque tengo algunas dudas, por éso estaba probando tu aplicación/módulo.

En éste momento me está dando éste error:

'''ImportError at /mp/checkout/product-1/
No module named full.path.to.checkout.builder.implementation
Request Method: GET
Request URL:    http://127.0.0.1:9001/mp/checkout/product-1/'''

Entiendo que deberia sustituir por mis datos de checkout, correcto?

Por otro lado, en settings,py coloqué el checkout en modo 'False'.

Más o menos que podria hacer para que no me salga éste error? Que datos debo sustituir?

Saludos y Gracias.

**Comment by hgdeoro** [comment]
Fijate en https://github.com/data-tsunami/django-mercadopago/blob/master/sample_project/sample_app/models.py, la funcion `update_checkout_preference()` es un ejemplo de como cargar los datos de _checkout preference_.

El valor  de _CHECKOUT_PREFERENCE_UPDATER_FUNCTION_ deberia referenciar a esa funcion, en este caso, sería algo como `sample_app.models.update_checkout_preference`

En el transcurso del dia actualizaré el README para que esto quede mas claro

**Comment by kkoci** [comment]
Gracias! Ok, mientras tanto haré unas pruebas

**Comment by hgdeoro** [comment]
README updated
