### ISSUE TITLE
django-mercadopago on PyPI

### ISSUE THREAD

**Issue by WhyNotHugo** [data-tsunami/django-mercadopago#4]
I've been maintaining [django-mercadopago-simple](https://pypi.python.org/pypi/django-mercadopago-simple) since early 2015, and only really picked that name since this project had the `django-mercadopago`name taken.

Since this project hasn't seen any activity since, and also won't work on recent versions of django/python, I was wondering if you were willing to "give up" the name `django-mercadopago` on PyPI so that my own project may adopt it.

Do you think that's possible? Would it be too much of a fuss?

Thanks!

**Comment by hgdeoro** [comment]
Sure! But I have no idea  how to do it. Do you have any documentation for "transferring" project names?

**Comment by WhyNotHugo** [comment]
Thanks for being open to this!

Roles for project names can by edited [here](https://pypi.python.org/pypi?:action=role_form&package_name=django-mercadopago). My PyPI username is `hobarrera`.

Again, thanks.

**Comment by hgdeoro** [comment]
Sorry for the delay. I added you as owner. Good luck!

**Comment by WhyNotHugo** [comment]
Big thanks! 🎉  Cheers!
